apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
spec:
  serviceName: mysql-master
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: master
  template:
    metadata:
      labels:
        app: mysql
        role: master
    spec:
      containers:
      - name: mysql
        image: bitnami/mysql:8.0
        env:
        # Senha de root
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        # Modo MASTER
        - name: MYSQL_REPLICATION_MODE
          value: "master"
        # Usuário e senha de replicação
        - name: MYSQL_REPLICATION_USER
          value: "repl_user"
        - name: MYSQL_REPLICATION_PASSWORD
          value: "repl_pass"
        # Configurações do seu banco / usuário da aplicação
        - name: MYSQL_USER
          value: "pocuser"
        - name: MYSQL_PASSWORD
          value: "pocpass"
        - name: MYSQL_DATABASE
          value: "pocdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /bitnami/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2  # ou gp3, etc. Ajuste ao seu cluster
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
spec:
  selector:
    app: mysql
    role: master
  ports:
  - port: 3306
    name: mysql
  # Headless Service para StatefulSet
  clusterIP: None
